# Application Constants

# Database Constants
DB_ECHO = True
DB_POOL_SIZE = 10
DB_MAX_OVERFLOW = 20

# JWT Constants
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 7

# Password Constants
MIN_PASSWORD_LENGTH = 8
PASSWORD_HASH_ALGORITHM = "bcrypt"

# Component Status Constants
COMPONENT_STATUS_DRAFT = "draft"
COMPONENT_STATUS_PUBLISHED = "published"
COMPONENT_STATUS_ARCHIVED = "archived"
COMPONENT_STATUSES = [
    COMPONENT_STATUS_DRAFT,
    COMPONENT_STATUS_PUBLISHED,
    COMPONENT_STATUS_ARCHIVED
]

# User Role Constants
USER_ROLE_ADMIN = "admin"
USER_ROLE_USER = "user"
USER_ROLES = [USER_ROLE_ADMIN, USER_ROLE_USER]

# Feedback Status Constants
FEEDBACK_STATUS_NEW = "new"
FEEDBACK_STATUS_IN_PROGRESS = "in_progress"
FEEDBACK_STATUS_RESOLVED = "resolved"
FEEDBACK_STATUS_CLOSED = "closed"
FEEDBACK_STATUSES = [
    FEEDBACK_STATUS_NEW,
    FEEDBACK_STATUS_IN_PROGRESS,
    FEEDBACK_STATUS_RESOLVED,
    FEEDBACK_STATUS_CLOSED
]

# API Response Constants
API_VERSION = "v1"
PROJECT_NAME = "ReactHub API"
PROJECT_DESCRIPTION = "Component Library Marketplace API"

# Pagination Constants
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

# Environment Constants
ENVIRONMENT_DEVELOPMENT = "development"
ENVIRONMENT_STAGING = "staging"
ENVIRONMENT_PRODUCTION = "production"
