"""Add rating column to feedback table

Revision ID: a10f8ebbd735
Revises: 
Create Date: 2026-04-11 18:07:06.180608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10f8ebbd735'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('rating', sa.Integer(), nullable=True))
    op.alter_column('feedback', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('feedback', 'rating')
    # ### end Alembic commands ###
