"""Simplify component model - store only metadata in DB

Revision ID: f4cd4ab7abb7
Revises: f5abafb34eb2
Create Date: 2026-04-11 22:58:49.413241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4cd4ab7abb7'
down_revision: Union[str, Sequence[str], None] = 'f5abafb34eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('components', 'component_code_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('components', 'framework')
    op.drop_column('components', 'usage_code')
    op.drop_column('components', 'css_code')
    op.drop_column('components', 'install_cmd')
    op.drop_column('components', 'component_code')
    op.drop_column('components', 'preview_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('preview_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('components', sa.Column('component_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('components', sa.Column('install_cmd', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('components', sa.Column('css_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('components', sa.Column('usage_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('components', sa.Column('framework', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('components', 'component_code_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
