"""Add component_code_path column to components table

Revision ID: f5abafb34eb2
Revises: a10f8ebbd735
Create Date: 2026-04-11 22:37:31.557024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5abafb34eb2'
down_revision: Union[str, Sequence[str], None] = 'a10f8ebbd735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('component_code_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'component_code_path')
    # ### end Alembic commands ###
